# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
# Specify "os: linux" if this revision targets Amazon Linux
os: linux

files:
  - source: /
    destination: /home/ec2-user/pawstreet

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1000
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1600
      runas: root

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root
